export enum JobType {
	FULL_TIME = 'FULL_TIME',
	PART_TIME = 'PART_TIME',
	CONTRACT = 'CONTRACT',
	INTERNSHIP = 'INTERNSHIP',
	TEMPORARY = 'TEMPORARY',
}

export enum JobStatus {
	ACTIVE = 'ACTIVE',
	CLOSED = 'CLOSED',
	DELETE = 'DELETE',
}

export enum JobLocation {
	SEOUL = 'SEOUL',
	BUSAN = 'BUSAN',
	INCHEON = 'INCHEON',
	DAEGU = 'DAEGU',
	GYEONGJU = 'GYEONGJU',
	GWANGJU = 'GWANGJU',
	CHONJU = 'CHONJU',
	DAEJON = 'DAEJON',
	JEJU = 'JEJU',
	REMOTE = 'REMOTE',
}

export enum JobCategory {
	IT = 'IT',
	FINANCE = 'FINANCE',
	EDUCATION = 'EDUCATION',
	HEALTHCARE = 'HEALTHCARE',
	ENGINEERING = 'ENGINEERING',
	MARKETING = 'MARKETING',
	SALES = 'SALES',
	CUSTOMER_SERVICE = 'CUSTOMER_SERVICE',
	HUMAN_RESOURCES = 'HUMAN_RESOURCES',
	MANUFACTURING = 'MANUFACTURING',
	HOSPITALITY = 'HOSPITALITY',
	CONSTRUCTION = 'CONSTRUCTION',
	TRANSPORTATION = 'TRANSPORTATION',
	OTHER = 'OTHER',
}
